config/routes.rb
Jobster::Application.routes.draw do
  
  resources :friendships, :memberships, :comments, :likes, :requests, :profiles, :preferences, :jobs
  
  resources :posts, :only => [:create, :destroy] do 
  	resources :comments
  	resources :likes
  end 
  
  resource :profile do 
  	resources :abouts
  	resources :preferences
  	resources :educations
  	resources :experiences
  	resources :competencies
  	resources :languages
  	resources :references
  end
  	
  get "home/show"
  get "home/landing"
  
  resources :activities do 
  	resources :comments
  	resources :likes
  end
  
  resources :statuses do 
  	resources :comments
  	resources :likes
  end
  
  resources :pages do 
  	resources :comments
  	resources :likes
  end
  
  resources :users do
  	#get :profile, :on => :collection  
  	get :change_profile, :on => :collection 
  	resources :pages
  end
  
  resources :events do
  	get :add, :on => :collection
  	put :assistance, :on => :collection
  	#post :page, :on => :collection
  	resources :pages
  end 	
  
  resources :groups do 
  	resources :pages
  end
  
  resources :messages do 
  	collection do 
  	  get :all
  	  get :inbox
  	  get :sentbox
  	  get :trash
  	end
  	resources :replies
  end

  
  devise_for :users do
    get "/login", :to => "devise/sessions#new"
    get "/logout", :to => "devise/sessions#destroy"
    get "/register", :to => "registrations#new"
  end
  
  match '/user/:username',
            :controller => 'users',
            :action => 'show_by_username' 
  
  match '/pages',
            :controller => 'pages',
            :action => 'index' 
            
  match '/contacts' => "contacts#contacts"
  
  match 'contacts/:id' => "contacts#contacts_user"
  
  match 'request/:user_id' => "requests#send_request"                                              
  match 'requests/pending' => "requests#pending"
  match 'profiles/:profile_id/preference/new' => "preferences#new"
  match 'profiles/:profile_id/education/new' => "educations#new"
  match 'profiles/:profile_id/experience/new' => "experiences#new"
  match 'profiles/:profile_id/competency/new' => "competencies#new"
  match 'profiles/:profile_id/language/new' => "languages#new"
  match 'profiles/:profile_id/reference/new' => "references#new"
            
  root :to => "home#show"            

  #match ':controller(/:action(/:id(.:format)))'
end

app/models/job.rb
class Job < ActiveRecord::Base
  attr_accessible :job_title, :job_type, :job_category, :working_location, :responsability, 
  :lowest_education_level, :highest_education_level, :age_min, :age_max, :salary_min, :salary_max,
  :negotiable, :travel, :relocate, :address, :latitude, :longitude	
  geocoded_by :address
  after_validation :geocode, :if => :address_changed?			
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController#< InheritedResources::Base
   def index
    @user = current_user
  	@jobs = Job.all
  	respond_to do |format| 
  	  format.html
  	  format.json { render :json => @jobs.map(&:attributes)}#.each {|h| h.dup.map { |k,v| [k.gsub!("jobname", "name"), v] }} }	
  	end
  end

  def new
    @user = current_user
  	@job = Job.new
  end

  def create
    @job = Job.new(params[:job])
    if @job.save
      flash[:notice] = "Successfully created job." 
      redirect_to @job, :notice => 'Successfully registered. You can join with your account now...'
    else
      flash[:notice] = "Couldn't create job." 	
      render :action => 'new'
    end
  end

  def show
  	@job = Job.find(params[:id])
  	@user = current_user
  end
  
  def edit
    @user = current_user
    @job = Job.find(params[:id])
  end

   def update
    @job = Job.find(params[:id])
    
    if @job.update_attributes(params[:job])
      flash[:notice] = "Successfully updated job."
      redirect_to jobs_path
    else
      render :action => 'edit'
    end
  end
  
 
  def destroy
    @job = Job.find(params[:id])
    @job.destroy
    redirect_to jobs_url, :notice => "Successfully destroyed job."
  end	
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_form.haml
= form_for(@job) do |f| 
  
  = f.label :job_title 
  
  = f.text_field :job_title 
  This is a job title
  %br
  
  = f.label :job_type 
  
  = f.text_field :job_type 
  %br
  
  = f.label :job_category 
  
  = f.text_field :job_category 
  %br
  
  = f.label :working_location 
  
  = f.text_field :working_location 
  %br

  = f.label :address 
  
  = f.text_field :address 
  %br
  = f.label :longitude 
  
  = f.text_field :longitude 
  %br
  = f.label :latitude  
  
  = f.text_field :latitude  
  %br
  
  = f.label :responsability 
  
  = f.text_area :responsability, :rows => 10, :cols => 100 
  %br
  
  = f.label :lowest_education_level 
  
  = f.text_field :lowest_education_level 
  %br
  
  = f.label :highest_education_level 
  
  = f.text_field :highest_education_level 
  %br
  
  = f.label :age_min 
  
  = f.text_field :age_min 
  %br
  
  = f.label :age_max 
  
  = f.text_field :age_max 
  %br
  
  = f.label :salary_min 
  
  = f.text_field :salary_min 
  %br
  = f.label :salary_max 
  
  = f.text_field :salary_max 
  %br
  = f.check_box :negotiable 
  %h5 negotiable
  %br
  = f.check_box :travel 
  %h5 travel
  %br
  = f.check_box :relocate 
  %h5 relocate
  %br
  = f.submit 
  

app/views/jobs/_job.haml
.display 
  %table 
    %tr 
      %td
        
           
        = @job.job_type 
        %br   
        %b Categorized under 
        = @job.job_category
        %br  
        %b Travel:
        = @job.travel
        %br 
        %b Relocate:
        = @job.relocate  
        %br   
        %b Education: 
        = @job.lowest_education_level
             
         
      %td
        .salary_min 
          Min
          $ 
          = @job.salary_min 
          
        .salary_max 
          Max 
          $ 
          = @job.salary_max 
        %p 
          Negotiable
          = @job.negotiable 
         
      
    
  #job_desc_wrapper
    .job_desc
    %h2 Job description 
    
    .textilize
      %p 
        %b 
          %ins Description 
        %br
        = @job.responsability
       
      
       
     
    
  .job_location 
    %h3 Working location
    = @job.working_location
    %br
    = image_tag "http://maps.google.com/maps/api/staticmap?size=450x300&sensor=false&zoom=16&markers=#{@job.latitude}%2C#{@job.longitude}"    
   
 
 
 

app/views/jobs/edit.haml
= render :partial => '/home/top'
.span-24.last
  .span-3
    %img.span-3{:src => gravatar_for(current_user)}
    = render :partial => '/home/links'
  .span-21.last
    %h3 Edit a job here
    = render 'form'

app/views/jobs/index.haml
%h1 Listing jobs

%table
  %tr
    %th Job title
    %th Job type
    %th Job category
    %th Working location
    %th Responsability
    %th Lowest education level
    %th Highest education level
    %th Age min
    %th Age max
    %th Salary min
    %th Salary max
    %th Negotiable
    %th Travel
    %th Relocate

- @jobs.each do |job| 
  %tr
    %td = job.job_title 
    %td = job.job_type 
    %td = job.job_category 
    %td = job.working_location 
    %td = job.responsability 
    %td = job.lowest_education_level 
    %td = job.highest_education_level 
    %td = job.age_min 
    %td = job.age_max 
    %td = job.salary_min 
    %td = job.salary_max 
    %td = job.negotiable 
    %td = job.travel 
    %td = job.relocate 
    %td = link_to 'Show', job 
    %td = link_to 'Edit', edit_job_path(job) 
    %td = link_to 'Destroy', job, :confirm => 'Are you sure?', :method => :delete 
 

%br

= link_to 'New Job', new_job_path 

app/views/jobs/new.haml
= render :partial => '/home/top'
.span-24.last
  .span-3
    %img.span-3{:src => gravatar_for(@user)}
    = render :partial => '/home/links'
  .span-21.last
    %h3 Create a job here
    = render 'form'

app/views/jobs/show.haml
= render :partial => '/home/top'
.span-24.last
  .span-3
    %img.span-3{:src => gravatar_for(@user)}
    = render :partial => '/home/links'
  .span-21.last
    %h3 
      = @job.job_title

    = render 'job'