config/routes.rb
Jobster::Application.routes.draw do
  
  resources :friendships, :memberships, :comments, :likes, :requests, :profiles, :preferences, :jobs
  
  resources :posts, :only => [:create, :destroy] do 
  	resources :comments
  	resources :likes
  end 
  
  resource :profile do 
  	resources :abouts
  	resources :preferences
  	resources :educations
  	resources :experiences
  	resources :competencies
  	resources :languages
  	resources :references
  end
  	
  get "home/show"
  get "home/landing"
  
  resources :activities do 
  	resources :comments
  	resources :likes
  end
  
  resources :statuses do 
  	resources :comments
  	resources :likes
  end
  
  resources :pages do 
  	resources :comments
  	resources :likes
  end
  
  resources :users do
  	#get :profile, :on => :collection  
  	get :change_profile, :on => :collection 
  	resources :pages
  end
  
  resources :events do
  	get :add, :on => :collection
  	put :assistance, :on => :collection
  	#post :page, :on => :collection
  	resources :pages
  end 	
  
  resources :groups do 
  	resources :pages
  end
  
  resources :messages do 
  	collection do 
  	  get :all
  	  get :inbox
  	  get :sentbox
  	  get :trash
  	end
  	resources :replies
  end

  
  devise_for :users do
    get "/login", :to => "devise/sessions#new"
    get "/logout", :to => "devise/sessions#destroy"
    get "/register", :to => "registrations#new"
  end
  
  match '/user/:username',
            :controller => 'users',
            :action => 'show_by_username' 
  
  match '/pages',
            :controller => 'pages',
            :action => 'index' 
            
  match '/contacts' => "contacts#contacts"
  
  match 'contacts/:id' => "contacts#contacts_user"
  
  match 'request/:user_id' => "requests#send_request"                                              
  match 'requests/pending' => "requests#pending"
  match 'profiles/:profile_id/preference/new' => "preferences#new"
  match 'profiles/:profile_id/education/new' => "educations#new"
  match 'profiles/:profile_id/experience/new' => "experiences#new"
  match 'profiles/:profile_id/competency/new' => "competencies#new"
  match 'profiles/:profile_id/language/new' => "languages#new"
  match 'profiles/:profile_id/reference/new' => "references#new"
            
  root :to => "home#show"            

  #match ':controller(/:action(/:id(.:format)))'
end

app/models/group.rb
class Group < ActiveRecord::Base
  
  has_many :memberships
  has_many :members, :class_name => 'User',
                     :through => :memberships
  has_many :pages, :as => :pageable	
  
  belongs_to :user
  belongs_to :wall
  
  after_create :create_wall
  after_create :add_activity
  
  def create_wall
    self.wall = Wall.create
    self.save
  end

  def add_activity
    Activity.create(:user_id => self.user.id, :activity_type => 'group', :text => "<a href='/user/#{self.user.username}'>#{self.user.formatted_name}</a> created a new group - <a href='/groups/#{self.id}'>#{self.name}</a>.")
  end  
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def index
  	@user = current_user
  	@groups = Group.all
  end

  def new
  	@user = current_user
  	@group = Group.new
  end

  def show
  	@user = current_user
  	@group = Group.find(params[:id])
  	@post = Post.new if @user
  	@page = Page.new if @user
  	@membership = Membership.where(:member_id => @user.id, :group_id => @group.id)
  end

  def join
  	@user = current_user
  	@group = Group.find(params[:id])
  	@group.members << @user
  	redirect_to @group
  end

  def create
  	@user = current_user
  	@group = current_user.groups.build(params[:group])
  	#@group.members << @user
  	if @group.save
  	  @membership = @user.memberships.create(:member_id => @user.id, :group_id => @group.id)	
  	  redirect_to @group, :notice => 'Group created successfully...'
  	else
  	  render :action => 'new', :notice => 'Cannot create the group...'	   	
  	end
  end
  
  def leave 
  	@user = current_user
    @group = Group.find(params[:id])
    if @group.members.include?(@user)
      @group.members.delete(@user)
      @group.save	
    end	
    redirect_to @group
  end
  
  def update
    @group.attributes = params[:group]
    if @page.save!
      redirect_to :back, :notice => "Updated..."
    else 
      redirect_to :action => "index"
    end
  end
  
  def destroy
  	@group = Group.find(params[:id])
  	@group.destroy
  	redirect_to groups_path
  end

end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/add.html.erb
<h1>Groups#add</h1>
<p>Find me in app/views/groups/add.html.erb</p>

app/views/groups/create.html.erb
<h1>Groups#create</h1>
<p>Find me in app/views/groups/create.html.erb</p>

app/views/groups/index.html.haml
= render '/home/top'
.span-24
  .span-3
    %img.span-3{:src => "#{@user.photo_url.nil? ? "http://www.gravatar.com/avatar/#{Digest::MD5.hexdigest(@user.email)}" : @user.photo_url }"}
    =render '/home/links'    
  .span-15
    %hr.space
    .span-3
      %div.icons.icons_group
      %strong{:style => 'vertical-align:bottom;font-size:18px;'} Groups
    .span-8 &nbsp;
    .span-4.last.right
      = link_to  "new group", new_group_path
    
    .span-15      
      %hr.space
      - @user.groups.each do |group|
        .span-11
          %strong #{group.name}
          .quiet #{group.description}
        .span-4.last{:style => 'text-align:right;'}
          - if group.user == @user
            = link_to 'delete', group_path(group), :method => :delete, :confirm => 'Are you sure you wish to delete this page?'
            = link_to 'view', group_path(group)
          - else 
            = link_to 'view', group_path(group)  
        %hr.space
        %hr
      
  .span-6.last
    %h3  Suggestions
    - if @user.friend_groups.empty?
      No suggested groups
    - else
      Your friends have joined the following groups:
      %ul
        - @user.friend_groups[0..9].each do |group|
          %li
            %a{:href => "/groups/#{group.id}"} #{group.name}

app/views/groups/leave.html.erb
<h1>Groups#leave</h1>
<p>Find me in app/views/groups/leave.html.erb</p>

app/views/groups/new.html.haml
=render '/home/top'

.span-24
  .span-3
    %img.span-3{:src => "#{@user.photo_url.nil? ? "http://www.gravatar.com/avatar/#{Digest::MD5.hexdigest(@user.email)}" : @user.photo_url }"}
    =render '/home/links'
  .span-20
    %h3 Create a new group
    Create a new group here, use it to share information!

    = form_for @group do |f|
      = f.label :name
      = f.text_field :name, :size => 45
      %br
      = f.label :description
      = f.text_area :description, :cols => 113, :rows => 7
      %br
      = f.submit "create"

app/views/groups/show.html.haml
=render '/home/top'
.span-24
  .span-3
    %img.span-3{:src => "#{@user.photo_url.nil? ? "http://www.gravatar.com/avatar/#{Digest::MD5.hexdigest(@user.email)}" : @user.photo_url }"}
    =render '/home/links'    
  .span-15
    
    %h3 #{@group.name}
    =@group.description
      
    %h3 Members
    - @group.members.each do |user|
      .span-1
        %a{:href => "/user/#{user.username}"}
          %img.span-1{:src => "#{user.photo_url.nil? ? "http://www.gravatar.com/avatar/#{Digest::MD5.hexdigest(user.email)}" : user.photo_url }", :alt => "#{user.formatted_name}"} 
    

    %hr.space

    %h3 Pages
    .span-3.push-12.right
      - if @group.user == @user
        = link_to "new page", "/groups/#{@group.id}/pages/new"
    - @group.pages.each do |page|
      .span-11
        %strong 
          = link_to page.title, page_path(page)
        .quiet Date created : #{page.created_at.strftime "%I:%M %p, %d %b %Y"}
      .span-4.last.right
        - if @group.user == @user
          = link_to "del", page, :confirm => "Are you sure?", :method => :delete
          %br
          %a.button{:href => "/groups/#{@group.id}/pages/#{page.id}/edit"} edit
      %hr.space
      %hr          
    %hr.space
    
    %h3 Wall
    =render '/shared/group_wall_box'
      
    %hr.space
    
    -@group.wall.posts.each do |post|
      .span-2
        %img.span-2{:src => "#{post.user.photo_url.nil? ? "http://www.gravatar.com/avatar/#{Digest::MD5.hexdigest(post.user.email)}" : post.user.photo_url }"}
      .span-4
        #{post.user.formatted_name}
        %br
        #{post.created_at.strftime "%d %b %Y"}
        %br
        #{post.created_at.strftime "%I:%M %P"}
      .span-8
        #{post.text}
      %hr
    %hr.space  

  .span-6.last
    %h3 Group admin
    .span-3
      %img.span-3{:src => "#{@group.user.photo_url.nil? ? "http://www.gravatar.com/avatar/#{Digest::MD5.hexdigest(@group.user.email)}" : @group.user.photo_url }"}  
      %a{:href => "/user/#{@group.user.username}"} #{@group.user.formatted_name}
    %hr.space
    %h3 Your membership
    =render '/shared/join_group'