config/routes.rb
Jobster::Application.routes.draw do
  
  resources :friendships, :memberships, :comments, :likes, :requests, :profiles, :preferences, :jobs
  
  resources :posts, :only => [:create, :destroy] do 
  	resources :comments
  	resources :likes
  end 
  
  resource :profile do 
  	resources :abouts
  	resources :preferences
  	resources :educations
  	resources :experiences
  	resources :competencies
  	resources :languages
  	resources :references
  end
  	
  get "home/show"
  get "home/landing"
  
  resources :activities do 
  	resources :comments
  	resources :likes
  end
  
  resources :statuses do 
  	resources :comments
  	resources :likes
  end
  
  resources :pages do 
  	resources :comments
  	resources :likes
  end
  
  resources :users do
  	#get :profile, :on => :collection  
  	get :change_profile, :on => :collection 
  	resources :pages
  end
  
  resources :events do
  	get :add, :on => :collection
  	put :assistance, :on => :collection
  	#post :page, :on => :collection
  	resources :pages
  end 	
  
  resources :groups do 
  	resources :pages
  end
  
  resources :messages do 
  	collection do 
  	  get :all
  	  get :inbox
  	  get :sentbox
  	  get :trash
  	end
  	resources :replies
  end

  
  devise_for :users do
    get "/login", :to => "devise/sessions#new"
    get "/logout", :to => "devise/sessions#destroy"
    get "/register", :to => "registrations#new"
  end
  
  match '/user/:username',
            :controller => 'users',
            :action => 'show_by_username' 
  
  match '/pages',
            :controller => 'pages',
            :action => 'index' 
            
  match '/contacts' => "contacts#contacts"
  
  match 'contacts/:id' => "contacts#contacts_user"
  
  match 'request/:user_id' => "requests#send_request"                                              
  match 'requests/pending' => "requests#pending"
  match 'profiles/:profile_id/preference/new' => "preferences#new"
  match 'profiles/:profile_id/education/new' => "educations#new"
  match 'profiles/:profile_id/experience/new' => "experiences#new"
  match 'profiles/:profile_id/competency/new' => "competencies#new"
  match 'profiles/:profile_id/language/new' => "languages#new"
  match 'profiles/:profile_id/reference/new' => "references#new"
            
  root :to => "home#show"            

  #match ':controller(/:action(/:id(.:format)))'
end

app/views/shared/_album.haml
- if @viewed_user.photos.empty?
  #{@viewed_user.formatted_name} has not uploaded any photos yet.

- @viewed_user.photos[0..15].each do |photo|
  %a{:href => "/photo/#{photo.id}"}
    %img.span-1{:src => photo.url_thumbnail }

%hr.space
%a{:href => "/albums/#{@viewed_user.id}"} view all
    

app/views/shared/_comment_and_like.haml
.span-15.last
  .span-2
    = link_to "comments(#{commentable.comments.size})", '#', :onclick => "$('#comment_box_#{commentable.class.to_s}_#{commentable.id}').toggle();$('#comment_box_#{commentable.class.to_s}_#{commentable.id}').focus();"  
   
  .span-13.last
    = link_to "like", likes_path(:user_id => current_user.id, :likeable_type => commentable.class, :likeable_id => commentable.id, :author => current_user.username), :method => :post 	
    - unless commentable.likes.empty?
      = pluralize(commentable.likes.size, 'person')
      likes this.
      - commentable.likes.each do |like|
        - if commentable.likes.last != like
          = link_to like.author, "/user/#{like.author}"
        - else
          = 'and ' unless commentable.likes.size == 1
          = link_to like.author, "/user/#{like.author}"     
        
.span-13.hide.last{:id => "comment_box_#{commentable.class.to_s}_#{commentable.id}"}
  = form_for [commentable, Comment.new] do |f|
    = f.hidden_field :user_id, :value => current_user.id
    = f.text_area :text, :cols => 50, :rows => 2
    %br
    = f.submit 'comment'

%hr.space{:style => 'height: 1px'}    

- unless commentable.comments.empty? 
  .span-14.push-1.last
    - commentable.comments.each do |comment|
      .span-1
        %a{:href => "/user/#{comment.user.username}"}
          %img.span-1{:src => "#{comment.user.photo_url.nil? ? "http://www.gravatar.com/avatar/#{Digest::MD5.hexdigest(comment.user.email)}" : comment.user.photo_url }"}
      .span-12.last.comment_box
        #{comment.text}
        %br
        %em.quiet 
          =time_ago_in_words(comment.created_at.to_time)

app/views/shared/_event_wall_box.haml
=render 'shared/text_limiter_js'
What's on your mind?
%form{ {:controller => 'event', :action => 'post_wall'}, :method => 'post'}
  %textarea.update.span-15#update{:name => 'status', :rows => 2, :cols => 107, :onKeyDown => "text_limiter($('#update'), $('#counter'))"}
  .span-6
    %span#counter
      160
    characters left
  .prepend-12
    %input{:type => 'hidden', :name => 'wall_id', :value => "#{@event.wall.id}"}
    %input{:type => 'hidden', :name => 'event_id', :value => "#{@event.id}"}
    %input{:type => 'hidden', :name => 'user_id', :value => "#{current_user.id}"}
    %input#button{:type => 'submit', :value => 'update'}

app/views/shared/_events.haml
- if @user.confirmed_events.empty?
  You are not going to any events.

- else
  You are going for the following events:
  %ul
  - @user.confirmed_events.each do |event|
    %li{:style => 'margin-left: 1.3em;'}
      %a{:href => "/events/#{event.id}"} #{event.name}

app/views/shared/_feeds.haml
.statuses
  -@all.each do |item|
    .span-1
      %img.span-1{:src => "#{item.user.photo_url.nil? ? "http://www.gravatar.com/avatar/#{Digest::MD5.hexdigest(item.user.email)}" : item.user.photo_url }"}
    .span-13.last
      %a{:href => "/user/#{item.user.username}"}
        =item.user.username
      &nbsp;
      = raw item.text

    .span-8.last
      %em.quiet
        =time_ago_in_words(item.created_at.to_time)
 
    =render 'shared/comment_and_like', :commentable => item
    %hr

app/views/shared/_group_wall_box.haml
What's on your mind?
= form_for @post do |f|
  .span-15
    = f.text_area :text, :rows => 2, :cols => 107, :id => 'update', :maxlength => 200, :autocomplete => :off
  .span-6
    %span#counter 160 characters left
  :javascript

    function pluralize_characters(num) {
      if(num == 1) {
        return num + " character";
      } else {
        return num + " characters";
      }
    }

    $("#update").keyup(function() {
      var chars = $("#update").val().length;
      var left = 160 - chars; // sub 160 for your max length
      if(left >= 0) {
        $("#counter").text(pluralize_characters(left) + " left");
      } else {
        left = left * (-1)
        $("#counter").text(pluralize_characters(left) + " too long");
      }
    });     
  .prepend-12
    = f.hidden_field :wall_id, :value => @group.wall.id 
    = f.submit 'update' 

app/views/shared/_groups.haml
- if @user.groups.empty?
  You don't belong to any groups.
- else
  %ul
    - @user.groups[0..4].each do |g|
      %a{:href => "/group/#{g.id}"}
        %li #{g.name}

%hr.space{:style => 'height: 1px;'}    
%a{:href => "/groups"} view all

app/views/shared/_join_group.haml
- if @group.members.include? @user
  You are a member of this group.
  - unless @group.user == @user
    - @user.memberships.each do |m|
      - @member = m if m.group_id == @group.id
    = link_to "leave this group", @member , :method => :delete 
  
- else
  You are not a member of this group yet.
  = button_to "Join this Group", memberships_path(:member_id => @user, :group_id => @group), :method => :post
    

app/views/shared/_pages.haml
- if @viewed_user.pages.empty?
  #{@viewed_user.formatted_name} has no pages.
%ul
  - @viewed_user.pages.each do |page|
    %li 
      %a{:href => "/pages/#{page.id}"}#{page.title}
      

app/views/shared/_requests.haml
- unless @user.requests.empty?
  .icons.icons_add_friend
  %a{:href => '/requests/pending'}    
    You have #{@user.requests.size} friend request(s). 
- else
  No pending friend requests
%br
- unless @user.pending_events.empty?
  .icons.icons_event
  %a{:href => '/events'}    
    You have #{@user.pending_events.size} pending event(s). 
- else
  No pending event

app/views/shared/_text_limiter_js.haml
:javascript
  function text_limiter(field,counter_field) {
    limit = 159;
    if (field.val().length > limit) 
      field.val(field.val().substring(0, limit));
    else
      counter_field.text(limit - field.val().length);
  }

app/views/shared/_update_box.haml
What's on your mind?
= form_for Status.new do |f|
  .span-15
    = f.text_area :text, :rows => 2, :cols => 107, :id => 'update', :maxlength => 200, :autocomplete => :off
    -# cols113
  .span-6
    %span#counter 160 characters left
  :javascript

    function pluralize_characters(num) {
      if(num == 1) {
        return num + " character";
      } else {
        return num + " characters";
      }
    }

    $("#update").keyup(function() {
      var chars = $("#update").val().length;
      var left = 160 - chars; // sub 160 for your max length
      if(left >= 0) {
        $("#counter").text(pluralize_characters(left) + " left");
      } else {
        left = left * (-1)
        $("#counter").text(pluralize_characters(left) + " too long");
      }
    });     
  .prepend-12
    = f.hidden_field :user_id, :value => @user.id 
    = f.submit 'update' 

app/views/shared/_wall_box.haml
What's on your mind?
= form_for Post.new do |f|
  .span-15
    = f.text_area :text, :rows => 2, :cols => 107, :id => 'update', :maxlength => 200, :autocomplete => :off
  .span-6
    %span#counter 160 characters left
  :javascript

    function pluralize_characters(num) {
      if(num == 1) {
        return num + " character";
      } else {
        return num + " characters";
      }
    }

    $("#update").keyup(function() {
      var chars = $("#update").val().length;
      var left = 160 - chars; // sub 160 for your max length
      if(left >= 0) {
        $("#counter").text(pluralize_characters(left) + " left");
      } else {
        left = left * (-1)
        $("#counter").text(pluralize_characters(left) + " too long");
      }
    });     
  .prepend-12
    = f.hidden_field :wall_id, :value => @viewed_user.wall.id    
    =# f.hidden_field :username, :value => @viewed_user.username    
    = f.submit 'update' 