config/routes.rb
Jobster::Application.routes.draw do
  
  resources :friendships, :memberships, :comments, :likes, :requests, :profiles, :preferences, :jobs
  
  resources :posts, :only => [:create, :destroy] do 
  	resources :comments
  	resources :likes
  end 
  
  resource :profile do 
  	resources :abouts
  	resources :preferences
  	resources :educations
  	resources :experiences
  	resources :competencies
  	resources :languages
  	resources :references
  end
  	
  get "home/show"
  get "home/landing"
  
  resources :activities do 
  	resources :comments
  	resources :likes
  end
  
  resources :statuses do 
  	resources :comments
  	resources :likes
  end
  
  resources :pages do 
  	resources :comments
  	resources :likes
  end
  
  resources :users do
  	#get :profile, :on => :collection  
  	get :change_profile, :on => :collection 
  	resources :pages
  end
  
  resources :events do
  	get :add, :on => :collection
  	put :assistance, :on => :collection
  	#post :page, :on => :collection
  	resources :pages
  end 	
  
  resources :groups do 
  	resources :pages
  end
  
  resources :messages do 
  	collection do 
  	  get :all
  	  get :inbox
  	  get :sentbox
  	  get :trash
  	end
  	resources :replies
  end

  
  devise_for :users do
    get "/login", :to => "devise/sessions#new"
    get "/logout", :to => "devise/sessions#destroy"
    get "/register", :to => "registrations#new"
  end
  
  match '/user/:username',
            :controller => 'users',
            :action => 'show_by_username' 
  
  match '/pages',
            :controller => 'pages',
            :action => 'index' 
            
  match '/contacts' => "contacts#contacts"
  
  match 'contacts/:id' => "contacts#contacts_user"
  
  match 'request/:user_id' => "requests#send_request"                                              
  match 'requests/pending' => "requests#pending"
  match 'profiles/:profile_id/preference/new' => "preferences#new"
  match 'profiles/:profile_id/education/new' => "educations#new"
  match 'profiles/:profile_id/experience/new' => "experiences#new"
  match 'profiles/:profile_id/competency/new' => "competencies#new"
  match 'profiles/:profile_id/language/new' => "languages#new"
  match 'profiles/:profile_id/reference/new' => "references#new"
            
  root :to => "home#show"            

  #match ':controller(/:action(/:id(.:format)))'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show
  	@user = current_user
    if @user
      #redirect_to :controller => 'aspects', :action => 'index'
      #:controller => 'pages', :action => 'index' 
      redirect_to :action => :landing#redirect_to current_user this doesn't run code!!
    else
      @landing_page = true
      #@user = User.new(:username => Digest::MD5.hexdigest(Time.now.to_s))
      #render :landing
      render :show
    end
  end
  
  def landing 
    @user = current_user
    @myself = @user
    @post = Post.new
    @all = @user.feed
  end
  
  def after_login
  	user = current_user 
    if user.new_record?
      photo = user[:photo].nil? ? "http://www.gravatar.com/avatar/#{Digest::MD5.hexdigest(user[:email])}" : user[:photo] 
      unless user.update_attributes({ :username => user[:username].hash.to_s(36), :email => user[:email], :photo_url => photo })
        flash[:error] = user.errors.values.join(",")
        redirect_to root_url
      end      
      session[:user_id] = user.id
      redirect_to edit_user_path(current_user.id)	
    else
      session[:user_id] = user.id
      redirect_to root_url  
    end  	  
  end

end

app/helpers/home_helper.rb
module HomeHelper
  def getting_started? 
  	current_user.profile
  end


  def smart_profile
    getting_started? ?  "/profiles/#{current_user.profile.id}" : '/profiles/new' 
  end		
end

app/views/home/_links.haml
- @user ||= current_user
%hr.space
.span-3
  .icons.icons_messages
  - num_unread_msgs =  @user.received_messages.where(:opened => false).size
  %a{:href => '/messages/inbox'} Messages 
  - if num_unread_msgs > 0
    (#{num_unread_msgs})
    
.span-3
  .icons.icons_event
  = link_to "Events", events_path
.span-3
  .icons.icons_photo
  %a{:href => '/albums'} Photos
.span-3
  .icons.icons_pages
  = link_to "Pages", pages_path
.span-3
  .icons.icons_group
  = link_to "Groups", groups_path        
.span-3
  .icons.icons_friends
  %a{:href => '/contacts'} Contacts
%hr.space

app/views/home/_nav.html.erb
<div id="user_nav">
        <% if user_signed_in? %>
          Signed in as <%= current_user.email %>. Not you?
          <%= link_to "Sign out", logout_path, :method => :delete %>  	
        <% else %>
          <%= link_to "Sign up", register_path %> or 
          <%= link_to "Sign in", login_path %>    	
        <% end %>  
      </div>

app/views/home/_top.haml
.span-24{:style => 'background: #3b5998 '}
  .span-2
    %a{:href => '/'} 
      %img{:src => '/images/jobster_header_main.png'}
  - if @user
    .comic.span-9.prepend-13.last
      %a.topbar{:href =>"/user/#{@user.username}"} #{@user.username.capitalize} -
      %a.topbar{:href => '/'} home -
      %a.topbar{:href => smart_profile }  profile - 
      %a.topbar{:href => '/contacts'}  contacts -  
      %a.topbar{:href => '/logout'}  logout       
  - else
    .span-2.prepend-20.last  
      %a.topbar{:href => '/register'} Sign in

app/views/home/landing.haml
=render 'home/top'

.span-24.last
  .span-3
    %img.span-3{:src => "#{@user.photo_url.nil? ? "http://www.gravatar.com/avatar/#{Digest::MD5.hexdigest(@user.email)}" : @user.photo_url }"}
    =render 'home/links'    
    
    %h3 Groups
    =render 'shared/groups'
    %h3 Contacts
    =render 'users/contacts', :user => @user
  .span-15
    
    %h3 News feed
    =render 'shared/update_box'
    %hr.space
    =render 'shared/feeds'
  
  .span-6.last
    %h3 Requests
    =render 'shared/requests'
    %h3 Reach out
    =render 'shared/invite'    
    %h3 Events
    =render 'shared/events'    
%hr.space

app/views/home/show.html.haml
=render :partial => 'nav'
.span-24
  .span-11
    %h1 Jobster
    = image_tag 'distributed.png', :width => 720, :height => 300
    .span-10.prepend-7
    %h2{:style => 'font-size:2em;margin-bottom:0.75em;margin-top:0; padding-top: 0;'} Connect with the biggest Companies in Bolivia, share your skills, Create your professional circle. Join Now!      
    .subtitle You don't need to register any accounts, just use an existing account from your favorite Internet provider!
  
    